[project]
name = "refashion"
version = "0.1.0"
description = ""
authors = [
    {name = "antoine-caillebotte",email = "caillebotte.antoine@cospirit.com"}
]

requires-python = ">=3.12, <3.15"
dependencies = [
    "mmm-utils @ file:///home/acaillebotte/projects/MMM/mmm_utils",
    "mmm-pptx @ file:///home/acaillebotte/projects/MMM/mmm_pptx",
    "pymongo (>=4.17.0,<5.0.0)",
    "numpyro (>=0.21.0,<0.22.0)",
    "arviz (>=1.2.0,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
mmm-utils = {develop = true}
mmm-pptx = {develop = true}

[dependency-groups]
dev = [
    "ipywidgets (>=8.1.8,<9.0.0)",
    "ipykernel (>=7.2.0,<8.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "sqlalchemy (>=2.0.49,<3.0.0)",
    "pymssql (>=2.3.13,<3.0.0)",
    "notebook (>=7.5.6,<8.0.0)",
    "graphviz (>=0.21,<0.22)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
]
